### ISSUE TITLE
Hacer que las llamadas a la API devuelvan y reciban datos

### ISSUE THREAD

**Issue by DavidGonzalezFernandez** [Arquisoft/lomap_es1c#19]
No hace falta que la API se lea ni escriba información en los POD.

Comenzar con unos datos hardcodeados y hacer que la API sea capaz de devolver la información solicitada, modificar, eliminar o añadir acorde a las llamadas realizadas.

La idea de esto es comprobar que la comunicación con la API se realiza de forma correcta y que hemos especificado todas las llamadas que la aplicación necesita.

**Comment by UO271497** [comment]
https://github.com/Arquisoft/lomap_es1c/commit/1107bbaec3fe8a8bdd2c0d95e50ec29990279d41
