### ISSUE TITLE
Comunicar el front-end con llamadas a la API

### ISSUE THREAD

**Issue by DavidGonzalezFernandez** [Arquisoft/lomap_es1c#31]
Definir la interfaz y la implementación por ambas partes, por la parte del backend la especificación de los datos enviados y por la parte del frontend la implementación de como enviar al backend los datos requeridos por este.

**Comment by UO271497** [comment]
https://github.com/Arquisoft/lomap_es1c/commit/1fac5770be1ec83f605fc4220ddf05d2c8fbeb83
Faltan llamadas por implementar pero los requisitos para añadirlas ya están.
