### ISSUE TITLE
Autoinforme Entregable 2

### ISSUE THREAD

**Issue by UO271497** [Arquisoft/lomap_es1c#50]
Miguel Suárez Artime

-  Desarrollo del backend excepto la parte de Solid.
- Creación de objetos modelo con los que trabajar internamente.
- Diseño de las llamadas a la restAPI (ubicadas en los archivos routes).
- Diseño de un sistema de autenticación a través de la restAPI.
- Diseño de los controladores que reciben las llamadas de la restAPI e interactúan con los datos (recoger datos de una llamada para crear una localización y con ellos crear el modelo e indicarle a la parte de Solid que cree el fichero). 
- Trato con políticas CORS para llamadas a la restAPI.

**Comment by uo284647** [comment]
Ruben Caño Dominguez
- Creacion de la estructura de datos en los PODs
- Escritura de localizaciones y reviews en los PODs
- Lectura de localizaciones y reviews en los PODs
- Eliminar localizaciones y reviews

**Comment by DavidGonzalezFernandez** [comment]
David González Fernández:

- Desarrollo y funcionalidad básica del menú lateral
- Creación del imagen y contenedor Docker

**Comment by UO283970** [comment]
Damián Fernández Álvarez

- Creación y visualización del mapa.
- Añadir puntos al mapa mediante un formulario y su visualización en el mapa.
