### ISSUE TITLE
Implementar llamada para devolver lugares del usuario

### ISSUE THREAD

**Issue by DavidGonzalezFernandez** [Arquisoft/lomap_es1c#72]
Definir la cabecera y retorno de la función que devuelve la información básica de todos los lugares del usuario

**Comment by UO271497** [comment]
https://github.com/Arquisoft/lomap_es1c/commit/29091e11d65cd13e1ef600be3dfe01f8fbe69b5a

**Comment by UO271497** [comment]
Falta implementar con SOLID, para otra issue
