### ISSUE TITLE
Implementar llamada para devolver toda la información sobre un lugar

### ISSUE THREAD

**Issue by DavidGonzalezFernandez** [Arquisoft/lomap_es1c#73]
Definir cabecera y retorno de la función que devuelve toda la información sobre un lugar

**Comment by UO271497** [comment]
https://github.com/Arquisoft/lomap_es1c/commit/29091e11d65cd13e1ef600be3dfe01f8fbe69b5a

Falta implementar con SOLID, para otra Issue
