### ISSUE TITLE
Implementar llamada para devolver la información básica de todos los lugares de todos los amigos

### ISSUE THREAD

**Issue by DavidGonzalezFernandez** [Arquisoft/lomap_es1c#74]
Definir cabecera y retorno de la función que devuelve un listado con la información básica de todos los lugares de todos los amigos de un usuario.

**Comment by UO271497** [comment]
https://github.com/Arquisoft/lomap_es1c/commit/1107bbaec3fe8a8bdd2c0d95e50ec29990279d41
