### ISSUE TITLE
Implementar llamada para devolver todas las categorías posibles

### ISSUE THREAD

**Issue by DavidGonzalezFernandez** [Arquisoft/lomap_es1c#78]
Definir cabecera y retorno de la llamada que devuelve el listado con todas las categorías posibles.

**Comment by UO271497** [comment]
https://github.com/Arquisoft/lomap_es1c/commit/75897374f8f4ded5cc3ed8a89794153432400482

Devuelve una lista hardcodeada, a revisar si en el futuro las categorías estarán en una bd centralizada.
